# Generated by Django 4.0.4 on 2022-05-29 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astronomical_observatory', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='observation',
            unique_together={('date', 'time', 'observatory_code')},
        ),
    ]
